#!/bin/bash
set -o errexit

scripts_dir=$(dirname $0)/scripts
source $scripts_dir/common_functions.sh
command="$1"

if [ "$command" == "model:download" ] ;then
  $scripts_dir/model/download_latest_model.sh
elif [ "$command" == "model:build-toy" ];then
  abort_if_model_already_loaded
  $scripts_dir/model/build_toy_model.sh
elif [ "$command" == "model:build-full" ];then
  abort_if_model_already_loaded
  $scripts_dir/model/download_training_data.sh
  $scripts_dir/model/download_usages.sh
  $scripts_dir/model/build_model.sh
elif [ "$command" == "model:status" ];then
  $scripts_dir/model/status_model.sh
elif [ "$command" == "model:backup" ];then
  $scripts_dir/model/backup_model.sh
elif [ "$command" == "model:delete" ];then
  $scripts_dir/model/delete_model.sh
elif [ "$command" == "web-app:start" ];then
  $scripts_dir/start_web_app.sh
elif [ "$command" == "web-app:stop" ];then
  docker-compose down
elif [ -n "$command" ] && [ "$command" != "--help" ]; then # if [not empty && not --help]
  echo "wsd: '$command' is not a wsd command."
  echo "See 'wsd --help'"
else
  echo ""
  echo "Usage: wsd COMMAND [OPTIONS]..."
  echo ""
  echo "A system for creating and serving word sense disambiguation models"
  echo ""
  echo "Model Commands"
  echo "  model:download     : download the latest model bundle form the web"
  echo "                       (recommended for normal usage)"
  echo "  model:build-toy    : builds a small toy model bundle within minutes"
  echo "  model:build-full   : downloads the training data and then builds the full model bundle"
  echo "                       (with 8 cores ~10h)"
  echo "  model:status       : provide information of the current model bundle"
  echo "  model:backup       : creates a backup of the current model bundle"
  echo "  model:delete       : deletes the current model bundle"
  echo ""
  echo "Serving Commands"
  echo "  web-app:start      : builds and then starts the web app"
  echo "                       (important: this requires a model, see Model Commands)"
  echo "  web-app:stop       : stops the web app"
  echo ""
fi
